require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

inherit_mode:
  merge:
    - Exclude
    - AllowedMethods

AllCops:
  TargetRubyVersion: 2.7.2
  NewCops: enable
  Exclude:
    - 'lib/**/*.rake'
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'coverage/**/*'
    - 'spec/*_helper.rb'
    - 'spec/factories/*.rb'
    - 'node_modules/**/*'
    - 'config/**/**'

Rails:
  Enabled: true

AsciiComments:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Metrics/AbcSize:
  Max: 40
  Exclude:
    - 'app/controllers/concerns/calculate.rb'

Metrics/CyclomaticComplexity:
  Max: 6

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 80

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'app/admin/**'

Style/AsciiComments:
  Enabled: false

# Respect RubyMine formatter
Layout/CaseIndentation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

# Name reduce block params |a, e|.
Style/SingleLineBlockParams:
  Enabled: false

# Respect RubyMine formatter
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

# Cannot deal with AR#eager_load
Style/SymbolProc:
  Enabled: false

# Final newline missing.
Layout/TrailingEmptyLines:
  Enabled: false

# 式展開しないときにはsingleを使う
Style/StringLiterals:
  EnforcedStyle: single_quotes

TrivialAccessors:
  Enabled: true
  ExactNameMatch: true

Layout/SpaceInsideBlockBraces:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/ArrayAlignment:
  Enabled: false

# Do not prefix writer method names with set_
Naming/AccessorMethodName:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging

RSpec/ExampleLength:
  Max: 8

RSpec/MultipleExpectations:
  Max: 5