version: '3'
services:
  db:
    image: postgres:11.5
    volumes:
      - datavol:/var/lib/postgresql/data
    ports:
      - 5432:5432
  app:
    build: .
    env_file: .docker-env
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
    depends_on:
      - db

volumes:
  datavol:
