common: &defaults
  name: <%= ENV["HEROKU_APP_NAME"] %>
  key: <%= ENV["SCOUT_KEY"] %>
  monitor: <%= ENV["SCOUT_MONITOR"] || true %>

test:
  monitor: false

development:
  monitor: false

staging:
  <<: *defaults

production:
  <<: *defaults