common: &defaults
  name: ENV["HEROKU_APP_NAME"]
  key: ENV["SCOUT_KEY"]
  log_level: info
  monitor: ENV["SCOUT_MONITOR"] || false

test:
  <<: *defaults
  monitor: false

development:
  <<: *defaults
  monitor: false

staging:
  <<: *defaults

production:
  <<: *defaults